### PR TITLE
fix whitespace

### PR DESCRIPTION
**Pull request by NotMoni**
fixed an extra space

### CODE REVIEW

**Comment by AnandChowdhary** [comment]
@NotMoni All these files are direct imports of my personal `.github`: https://github.com/AnandChowdhary/.github

If you find the time, I'd love it if you can help me by making the same PR there too :)

**Comment by NotMoni** [comment]
@AnandChowdhary  Will take a look for sure. 🦄

**Comment by AnandChowdhary** [comment]
If you have any ideas for new projects, or want to help us build our Deno projects, we'd love to have you part of @denorg!

**Comment by NotMoni** [comment]
@AnandChowdhary if it fine with the org owner then sure.
if not, all is well 🦄 😃

**Comment by yg** [comment]
@AnandChowdhary is the org owner 😻

**Comment by AnandChowdhary** [comment]
I just sent you an invitation!

**Comment by NotMoni** [comment]
@AnandChowdhary Thanks! I send a pr to your .github repo also 🦄

**Pull request merged**
